### ISSUE TITLE
Webpack Build fail with v1.6.0

### ISSUE THREAD

**Issue by insanehong** [Gbuomprisco/ngx-chips#630]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[0] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

build fail when build with v1.6.0

### app.module.ts 
```
import { TagInputModule } from 'ngx-chips';
```

### build fail

```
webpack 3.5.5
@angular/compiler-cli: 4.4.4

src/app/app.module.ts
Module not found: Can't resolve 'ngx-chips'
```
v1.5.11 is clean 

**Expected behavior**

**Minimal reproduction of the problem with instructions (if applicable)**

**What do you use to build your app?. Please specify the version**

```

```
**Angular version:** 

v4.4.4

**ngx-chips version:**

v1.6.0

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome

**Comment by geekscorner** [comment]
I experience the same issue. Fresh of an angular 5 project using ng new (angular cli 1.6).  
src/app/app.module.ts(3,32): error TS2307: Cannot find module 'ngx-chips'.

**Comment by mshamee** [comment]
Cannot find module 'ngx-chips' after doing npm install today. Can someone help what went wrong

**Comment by Gbuomprisco** [comment]
Hi, something is wrong with the latest release, lock the version to 1.5.11 for now, I'll have a look tomorrow

**Comment by elessariel** [comment]
seconded, pls fix.

**Comment by core-avatar** [comment]
and please try it out with yarn - building at install time is not supported there

**Comment by ejahn** [comment]
+1

**Comment by darkguy2008** [comment]
Same is happening over here :(

**Comment by Gbuomprisco** [comment]
just lock the version guys

**Comment by XemaA** [comment]
I have the same problem after upgrading to angular 5 ! any suggestions ! thanks.

**Comment by Gbuomprisco** [comment]
should be fixed with v1.6.1

**Comment by insanehong** [comment]
@Gbuomprisco fixed with v1.6.1. Thx

**Comment by XemaA** [comment]
@insanehong @Gbuomprisco Fixed ! thx
