### ISSUE TITLE
error TS2307: Cannot find module '../../modules'.

### ISSUE THREAD

**Issue by nasserghiasi** [Gbuomprisco/ngx-chips#805]
ERROR in node_modules/ngx-chips/core/accessor.d.ts(2,34): error TS2307: Cannot find module '../../modules'.
I importet TagInputModule in app.module.ts

PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**
![2018-08-26_13-42-10](https://user-images.githubusercontent.com/2284751/44626685-e2e7c100-a935-11e8-9d59-8961ddaa5809.jpg)
modules folder doesn't exist in latest version (1.9.5)

**Expected behavior**

**Minimal reproduction of the problem with instructions (if applicable)**

**What do you use to build your app?. Please specify the version**

**Angular version:** 

**ngx-chips version:**

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adnanmokhtar** [comment]
i got the same issue

**Comment by crane168** [comment]
I was demoted to version1.9.4 and the problem was solved。

**Comment by rvarlikli** [comment]
i got the same issue i change the version 1.9.4 but still not working

**Comment by Gbuomprisco** [comment]
Try v 1.9.6

**Comment by bartes** [comment]
<img width="1110" alt="screen shot 2018-08-27 at 13 52 35" src="https://user-images.githubusercontent.com/93064/44658293-95845600-aa00-11e8-9d4f-a8854f18ae59.png">
same problem here

**Comment by ashokdhasan** [comment]
Same issue here, ERROR in node_modules/ngx-chips/core/accessor.d.ts(2,34): error TS2307: Cannot find module '../../modules/components/dropdown/tag-input-dropdown.component'.

**Comment by DejanNemet** [comment]
I have the same issue:
**ERROR in node_modules/ngx-chips/core/accessor.d.ts(2,34): error TS2307: Cannot find module '../../components/dropdown/tag-input-dropdown.component'**

The problem is the path to the tag-input-dropdown.component is wrong...
I've changed the path in the "accessor.d.ts" file to: 
**import { TagInputDropdown } from '../components/dropdown/tag-input-dropdown.component';**
and now it works. But that is only a local solution... I don't have access to the server so there is no way for me to change the file...

Any tips?

**Comment by Zapopozapopo** [comment]
same

**Comment by eriendel** [comment]
It seems to be some issue with npm. Just try to clear npm cache and reinstall the package, rerun the project and it should be fine at least that worked for me.

**Comment by DejanNemet** [comment]
Clearing cache didn't work.
**npm cache clean --force**
deleted **package-lock.json** and **node-modules** folder before running _**npm install**_

Tried it on versions v1.9.3, v1.9.4, v1.9.5 and v1.9.6

**Comment by Ahmad-Magdy** [comment]
So i think it's better to stick with version `"ngx-chips": "1.9.4"` for now until they solve the problem

**Comment by bhaumikdarji** [comment]
We are using 1.8.0 version till thursday (23 Aug 2018) everything was fine. and suddenly on 24 Aug 2018 we are getting this issue.   
Any reason for that?

**Comment by bhaumikdarji** [comment]
sorry, my version is 1.9.6 
any way to fix it ?

**Comment by ashokdhasan** [comment]
Version 1.9.4 and 1.9.5 was working good yesterday, after installing modules package. But getting some other issues now. I think it is safe to go with v 1.6.5 for now.

**Comment by bhaumikdarji** [comment]
@ashokdhasan  I have installl modules but its not working.  Not sure how it working till Friday

**Comment by DejanNemet** [comment]
@ashokdhasan same here. I can't get it to work on any version... Funny thing is it was working with v 1.9.3. until yesterday...

**Comment by Gbuomprisco** [comment]
Just released 1.9.7. No time to try so if you guys can have a look now :)

**Comment by Lausselloic** [comment]
hello 1.9.7 seems to solve the problem on my project

**Comment by DejanNemet** [comment]
Nice. I can confirm, v 1.9.7. solves the **Cannot find module '../../modules'**  issue.
Thank you very much guys!
