### ISSUE TITLE
Cannot find name 'object'. webpack: Failed to compile.

### ISSUE THREAD

**Issue by rcadhikari** [Gbuomprisco/ngx-chips#512]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
~~[ ] feature request~~ [new feature requests are not considered at this time]
[ ] support request/question
```

**Current behavior**

```
ERROR in /Users/ram.adhikari/apps/expert-rates/frontend/node_modules/ngx-chips/dist/modules/components/tag-input/tag-input.d.ts (72,17): Cannot find name 'object'.
webpack: Failed to compile.
```

**Expected behavior**

**Minimal reproduction of the problem with instructions (if applicable)**

**What is the motivation / use case for changing the behavior? (if applicable)**

**What do you use to build your app?. Please specify the version**

Webpack v2.7.0, 
angular-cli v1.26,

**Angular version:** 

v4.3.2

**ngx-chips version:**

^1.4.6

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome XX(latest), Firefox XX (latest)

**Comment by Gbuomprisco** [comment]
TS >= 2.2 is required

**Comment by rcadhikari** [comment]
Doesn't work with `TSC v2.4.2`.

**Comment by Gbuomprisco** [comment]
can you paste a stacktrace and your package.json? sorry but it's very odd unless something changed in TS 2.4?

**Comment by rcadhikari** [comment]
Highlighted the issue caused by the script below:
![snip20170801_6](https://user-images.githubusercontent.com/988548/28836122-a51618c4-76df-11e7-9d7f-b29b941b6c49.png)

**Comment by rcadhikari** [comment]
Here is my `package.json` below:
```
{
  "name": "expert-rates-frontend",
  "description": "Expert Rates Frontend",
  "license": "Copyright (C) FTI Consulting, Inc. All rights reserved.",
  "version": "0.5.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.3.2",
    "@angular/common": "^4.3.2",
    "@angular/compiler": "^4.3.2",
    "@angular/core": "^4.3.2",
    "@angular/forms": "^4.3.2",
    "@angular/http": "^4.3.2",
    "@angular/platform-browser": "^4.3.2",
    "@angular/platform-browser-dynamic": "^4.3.2",
    "@angular/platform-server": "^4.3.2",
    "@angular/router": "^4.3.2",
    "@progress/kendo-angular-dateinputs": "^1.0.5",
    "@progress/kendo-angular-dropdowns": "^1.1.2",
    "@progress/kendo-angular-excel-export": "^1.0.3",
    "@progress/kendo-angular-grid": "^1.2.3",
    "@progress/kendo-angular-inputs": "^1.0.7",
    "@progress/kendo-angular-intl": "^1.2.2",
    "@progress/kendo-angular-l10n": "^1.0.2",
    "@progress/kendo-data-query": "^1.0.6",
    "@progress/kendo-drawing": "^1.1.2",
    "@telerik/kendo-theme-default": "^1.33.4",
    "angular2-material-datepicker": "^0.5.0",
    "animate.css": "3.1.1",
    "bootstrap": "^3.3.7",
    "chart.js": "^2.6.0",
    "core-js": "^2.4.1",
    "font-awesome": "^4.7.0",
    "jquery": "^3.1.0",
    "jquery-slimscroll": "^1.3.8",
    "jquery-sparkline": "^2.4.0",
    "jvectormap-next": "^3.0.0",
    "metismenu": "^2.5.0",
    "ng2-charts": "^1.6.0",
    "ngx-bootstrap": "^1.8.1",
    "ngx-chips": "^1.4.6",
    "peity": "^3.2.1",
    "rxjs": "^5.4.2",
    "zone.js": "^0.8.16"
  },
  "devDependencies": {
    "@angular/cli": "^1.2.6",
    "@angular/compiler-cli": "^4.3.2",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.85",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "^5.1.2",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.1.5",
    "webpack": "^2.7.0"
  }
}

```

**Comment by Gbuomprisco** [comment]
Update typescript (there is a tilde in the package json) so your version is fixed to 1.1

**Comment by rcadhikari** [comment]
Modifying the `"typescript": "~2.4.2"` to `"typescript": "^2.4.2"` resolved the issue.

Then ran the following:
```
rm -rf node_modules
npm cache clean --force
npm install
ng serve
```
Thank you @Gbuomprisco for help!!!

**Comment by kultigin** [comment]
I am also getting this error and  using "typescript": "2.1.5". 
Tried to upgrade/ change from ng2-tag-input plugin. Because custom theme was not working.

This is the error.
node_modules/ngx-chips/components/tag-input/tag-input.d.ts(305,17): Error TS2304: Cannot find name 'object'.
