### ISSUE TITLE
Getting error in ngx-chips dependency of ng2 material dropdown

### ISSUE THREAD

**Issue by anitha-optisol** [Gbuomprisco/ngx-chips#1026]
**I'm facing the below issue.** 
**Angular Version:9.1.9
Node version:12**
@Gbuomprisco                                                                                                                                                           
  #14 134.6 ERROR in node_modules/ngx-chips/node_modules/ng2-material-dropdown/src/modules/components/button/ng2-dropdown-button.d.ts:18:21 - error TS2694: Namespace '"/app/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.
#14 134.6
#14 134.6 18     static ɵfac: i0.ɵɵFactoryDeclaration<Ng2DropdownButton, never>;
#14 134.6                        ~~~~~~~~~~~~~~~~~~~~
#14 134.6 node_modules/ngx-chips/node_modules/ng2-material-dropdown/src/modules/components/button/ng2-dropdown-button.d.ts:19:21 - error TS2694: Namespace '"/app/node_modules/@angular/core/core"' has no exported member 'ɵɵComponentDeclaration'.
#14 134.6
#14 134.6 19     static ɵcmp: i0.ɵɵComponentDeclaration<Ng2DropdownButton, "ng2-dropdown-button", never, { "showCaret": "showCaret"; }, { "onMenuToggled": "onMenuToggled"; }, never, ["*"]>;
#14 134.6                        ~~~~~~~~~~~~~~~~~~~~~~
#14 134.6 node_modules/ngx-chips/node_modules/ng2-material-dropdown/src/modules/services/dropdown-state.service.d.ts:9:21 - error TS2694: Namespace '"/app/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.
#14 134.6
#14 134.6 9     static ɵfac: i0.ɵɵFactoryDeclaration<DropdownStateService, never>;
#14 134.6                       ~~~~~~~~~~~~~~~~~~~~
#14 134.6 node_modules/ngx-chips/node_modules/ng2-material-dropdown/src/modules/services/dropdown-state.service.d.ts:10:22 - error TS2694: Namespace '"/app/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectableDeclaration'.
#14 134.6
#14 134.6 10     static ɵprov: i0.ɵɵInjectableDeclaration<DropdownStateService>;
#14 134.6                         ~~~~~~~~~~~~~~~~~~~~~~~
#14 134.6 node_modules/ngx-chips/node_modules/ng2-material-dropdown/src/modules/components/menu-item/ng2-menu-item.d.ts:38:21 - error TS2694: Namespace '"/app/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.
#14 134.6
#14 134.6 38     static ɵfac: i0.ɵɵFactoryDeclaration<Ng2MenuItem, never>;
#14 134.6                        ~~~~~~~~~~~~~~~~~~~~
#14 134.6 node_modules/ngx-chips/node_modules/ng2-material-dropdown/src/modules/components/menu-item/ng2-menu-item.d.ts:39:21 - error TS2694: Namespace '"/app/node_modules/@angular/core/core"' has no exported member 'ɵɵComponentDeclaration'.
#14 134.6
#14 134.6 39     static ɵcmp: i0.ɵɵComponentDeclaration<Ng2MenuItem, "ng2-menu-item", never, { "preventClose": "preventClose"; "value": "value"; }, {}, never, ["*"]>;
#14 134.6                        ~~~~~~~~~~~~~~~~~~~~~~
#14 134.6 node_modules/ngx-chips/node_modules/ng2-material-dropdown/src/modules/components/menu/ng2-dropdown-menu.d.ts:74:21 - error TS2694: Namespace '"/app/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.
#14 134.6
#14 134.6 74     static ɵfac: i0.ɵɵFactoryDeclaration<Ng2DropdownMenu, never>;
#14 134.6                        ~~~~~~~~~~~~~~~~~~~~
#14 134.6 node_modules/ngx-chips/node_modules/ng2-material-dropdown/src/modules/components/menu/ng2-dropdown-menu.d.ts:75:21 - error TS2694: Namespace '"/app/node_modules/@angular/core/core"' has no exported member 'ɵɵComponentDeclaration'.
#14 134.6
#14 134.6 75     static ɵcmp: i0.ɵɵComponentDeclaration<Ng2DropdownMenu, "ng2-dropdown-menu", never, { "width": "width"; "focusFirstElement": "focusFirstElement"; "offset": "offset"; "appendToBody": "appendToBody"; "zIndex": "zIndex"; }, {}, ["items"], ["*"]>;
#14 134.6                        ~~~~~~~~~~~~~~~~~~~~~~
#14 134.6 node_modules/ngx-chips/node_modules/ng2-material-dropdown/src/modules/components/dropdown/ng2-dropdown.d.ts:38:21 - error TS2694: Namespace '"/app/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.
#14 134.6
#14 134.6 38     static ɵfac: i0.ɵɵFactoryDeclaration<Ng2Dropdown, never>;
#14 134.6                        ~~~~~~~~~~~~~~~~~~~~
#14 134.6 node_modules/ngx-chips/node_modules/ng2-material-dropdown/src/modules/components/dropdown/ng2-dropdown.d.ts:39:21 - error TS2694: Namespace '"/app/node_modules/@angular/core/core"' has no exported member 'ɵɵComponentDeclaration'.
#14 134.6
#14 134.6 39     static ɵcmp: i0.ɵɵComponentDeclaration<Ng2Dropdown, "ng2-dropdown", never, { "dynamicUpdate": "dynamicUpdate"; }, { "onItemClicked": "onItemClicked"; "onItemSelected": "onItemSelected"; "onShow": "onShow"; "onHide": "onHide"; }, ["button", "menu"], ["ng2-dropdown-button", "ng2-dropdown-menu"]>;
#14 134.6                        ~~~~~~~~~~~~~~~~~~~~~~
#14 134.6 node_modules/ngx-chips/node_modules/ng2-material-dropdown/src/modules/ng2-dropdown.module.d.ts:13:21 - error TS2694: Namespace '"/app/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.
#14 134.6
#14 134.6 13     static ɵfac: i0.ɵɵFactoryDeclaration<Ng2DropdownModule, never>;
#14 134.6                        ~~~~~~~~~~~~~~~~~~~~
#14 134.6 node_modules/ngx-chips/node_modules/ng2-material-dropdown/src/modules/ng2-dropdown.module.d.ts:14:21 - error TS2694: Namespace '"/app/node_modules/@angular/core/core"' has no exported member 'ɵɵNgModuleDeclaration'.
#14 134.6
#14 134.6 14     static ɵmod: i0.ɵɵNgModuleDeclaration<Ng2DropdownModule, [typeof i1.Ng2Dropdown, typeof i2.Ng2MenuItem, typeof i3.Ng2DropdownButton, typeof i4.Ng2DropdownMenu], [typeof i5.CommonModule], [typeof i2.Ng2MenuItem, typeof i3.Ng2DropdownButton, typeof i4.Ng2DropdownMenu, typeof i1.Ng2Dropdown]>;
#14 134.6                        ~~~~~~~~~~~~~~~~~~~~~
#14 134.6 node_modules/ngx-chips/node_modules/ng2-material-dropdown/src/modules/ng2-dropdown.module.d.ts:15:21 - error TS2694: Namespace '"/app/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectorDeclaration'.
#14 134.6
#14 134.6 15     static ɵinj: i0.ɵɵInjectorDeclaration<Ng2DropdownModule>;
#14 134.6                        ~~~~~~~~~~~~~~~~~~~~~
#14 134.6 node_modules/ngx-chips/components/dropdown/tag-input-dropdown.component.d.ts:191:21 - error TS2694: Namespace '"/app/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.
#14 134.6
#14 134.6 191     static ɵfac: i0.ɵɵFactoryDeclaration<TagInputDropdown, never>;
#14 134.6                         ~~~~~~~~~~~~~~~~~~~~
#14 134.6 node_modules/ngx-chips/components/dropdown/tag-input-dropdown.component.d.ts:192:21 - error TS2694: Namespace '"/app/node_modules/@angular/core/core"' has no exported member 'ɵɵComponentDeclaration'.
#14 134.6
#14 134.6 192     static ɵcmp: i0.ɵɵComponentDeclaration<TagInputDropdown, "tag-input-dropdown", never, { "offset": "offset"; "focusFirstElement": "focusFirstElement"; "showDropdownIfEmpty": "showDropdownIfEmpty"; "autocompleteObservable": "autocompleteObservable"; "minimumTextLength": "minimumTextLength"; "limitItemsTo": "limitItemsTo"; "displayBy": "displayBy"; "identifyBy": "identifyBy"; "matchingFn": "matchingFn"; "appendToBody": "appendToBody"; "keepOpen": "keepOpen"; "dynamicUpdate": "dynamicUpdate"; "zIndex": "zIndex"; "autocompleteItems": "autocompleteItems"; }, {}, ["templates"], never>;
#14 134.6                         ~~~~~~~~~~~~~~~~~~~~~~
#14 134.6 node_modules/ngx-chips/core/accessor.d.ts:42:21 - error TS2694: Namespace '"/app/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.
#14 134.6
#14 134.6 42     static ɵfac: i0.ɵɵFactoryDeclaration<TagInputAccessor, never>;
#14 134.6                        ~~~~~~~~~~~~~~~~~~~~
#14 134.6 node_modules/ngx-chips/core/accessor.d.ts:43:21 - error TS2694: Namespace '"/app/node_modules/@angular/core/core"' has no exported member 'ɵɵDirectiveDeclaration'.
#14 134.6
#14 134.6 43     static ɵdir: i0.ɵɵDirectiveDeclaration<TagInputAccessor, never, never, { "displayBy": "displayBy"; "identifyBy": "identifyBy"; }, {}, never>;
#14 134.6                        ~~~~~~~~~~~~~~~~~~~~~~
#14 134.6 node_modules/ngx-chips/core/providers/drag-provider.d.ts:63:21 - error TS2694: Namespace '"/app/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.
#14 134.6
#14 134.6 63     static ɵfac: i0.ɵɵFactoryDeclaration<DragProvider, never>;
#14 134.6                        ~~~~~~~~~~~~~~~~~~~~
#14 134.6 node_modules/ngx-chips/core/providers/drag-provider.d.ts:64:22 - error TS2694: Namespace '"/app/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectableDeclaration'.
#14 134.6
#14 134.6 64     static ɵprov: i0.ɵɵInjectableDeclaration<DragProvider>;
#14 134.6                         ~~~~~~~~~~~~~~~~~~~~~~~
#14 134.6 node_modules/ngx-chips/components/tag-input-form/tag-input-form.component.d.ts:129:21 - error TS2694: Namespace '"/app/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.
#14 134.6
#14 134.6 129     static ɵfac: i0.ɵɵFactoryDeclaration<TagInputForm, never>;
#14 134.6                         ~~~~~~~~~~~~~~~~~~~~
#14 134.6 node_modules/ngx-chips/components/tag-input-form/tag-input-form.component.d.ts:130:21 - error TS2694: Namespace '"/app/node_modules/@angular/core/core"' has no exported member 'ɵɵComponentDeclaration'.
#14 134.6
#14 134.6 130     static ɵcmp: i0.ɵɵComponentDeclaration<TagInputForm, "tag-input-form", never, { "placeholder": "placeholder"; "validators": "validators"; "asyncValidators": "asyncValidators"; "inputId": "inputId"; "inputClass": "inputClass"; "tabindex": "tabindex"; "disabled": "disabled"; "inputText": "inputText"; }, { "onSubmit": "onSubmit"; "onBlur": "onBlur"; "onFocus": "onFocus"; "onKeyup": "onKeyup"; "onKeydown": "onKeydown"; "inputTextChange": "inputTextChange"; }, never, never>;
#14 134.6                         ~~~~~~~~~~~~~~~~~~~~~~
#14 134.6 node_modules/ngx-chips/components/tag/tag-ripple.component.d.ts:4:21 - error TS2694: Namespace '"/app/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.
#14 134.6
#14 134.6 4     static ɵfac: i0.ɵɵFactoryDeclaration<TagRipple, never>;
#14 134.6                       ~~~~~~~~~~~~~~~~~~~~
#14 134.6 node_modules/ngx-chips/components/tag/tag-ripple.component.d.ts:5:21 - error TS2694: Namespace '"/app/node_modules/@angular/core/core"' has no exported member 'ɵɵComponentDeclaration'.
#14 134.6
#14 134.6 5     static ɵcmp: i0.ɵɵComponentDeclaration<TagRipple, "tag-ripple", never, { "state": "state"; }, {}, never, never>;
#14 134.6                       ~~~~~~~~~~~~~~~~~~~~~~
#14 134.6 node_modules/ngx-chips/components/tag/tag.component.d.ts:163:21 - error TS2694: Namespace '"/app/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.
#14 134.6
#14 134.6 163     static ɵfac: i0.ɵɵFactoryDeclaration<TagComponent, never>;
#14 134.6                         ~~~~~~~~~~~~~~~~~~~~
#14 134.6 node_modules/ngx-chips/components/tag/tag.component.d.ts:164:21 - error TS2694: Namespace '"/app/node_modules/@angular/core/core"' has no exported member 'ɵɵComponentDeclaration'.
#14 134.6
#14 134.6 164     static ɵcmp: i0.ɵɵComponentDeclaration<TagComponent, "tag", never, { "model": "model"; "removable": "removable"; "editable": "editable"; "template": "template"; "displayBy": "displayBy"; "identifyBy": "identifyBy"; "index": "index"; "hasRipple": "hasRipple"; "disabled": "disabled"; "canAddTag": "canAddTag"; }, { "onSelect": "onSelect"; "onRemove": "onRemove"; "onBlur": "onBlur"; "onKeyDown": "onKeyDown"; "onTagEdited": "onTagEdited"; }, never, never>;
#14 134.6                         ~~~~~~~~~~~~~~~~~~~~~~
#14 134.6 node_modules/ngx-chips/components/tag-input/tag-input.d.ts:486:21 - error TS2694: Namespace '"/app/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.
#14 134.6
#14 134.6 486     static ɵfac: i0.ɵɵFactoryDeclaration<TagInputComponent, never>;
#14 134.6                         ~~~~~~~~~~~~~~~~~~~~
#14 134.6 node_modules/ngx-chips/components/tag-input/tag-input.d.ts:487:21 - error TS2694: Namespace '"/app/node_modules/@angular/core/core"' has no exported member 'ɵɵComponentDeclaration'.
#14 134.6
#14 134.6 487     static ɵcmp: i0.ɵɵComponentDeclaration<TagInputComponent, "tag-input", never, { "separatorKeys": "separatorKeys"; "separatorKeyCodes": "separatorKeyCodes"; "placeholder": "placeholder"; "secondaryPlaceholder": "secondaryPlaceholder"; "maxItems": "maxItems"; "validators": "validators"; "asyncValidators": "asyncValidators"; "onlyFromAutocomplete": "onlyFromAutocomplete"; "errorMessages": "errorMessages"; "theme": "theme"; "onTextChangeDebounce": "onTextChangeDebounce"; "inputId": "inputId"; "inputClass": "inputClass"; "clearOnBlur": "clearOnBlur"; "hideForm": "hideForm"; "addOnBlur": "addOnBlur"; "addOnPaste": "addOnPaste"; "pasteSplitPattern": "pasteSplitPattern"; "blinkIfDupe": "blinkIfDupe"; "removable": "removable"; "editable": "editable"; "allowDupes": "allowDupes"; "modelAsStrings": "modelAsStrings"; "trimTags": "trimTags"; "inputText": "inputText"; "ripple": "ripple"; "tabindex": "tabindex"; "disable": "disable"; "dragZone": "dragZone"; "onRemoving": "onRemoving"; "onAdding": "onAdding"; "animationDuration": "animationDuration"; }, { "onAdd": "onAdd"; "onRemove": "onRemove"; "onSelect": "onSelect"; "onFocus": "onFocus"; "onBlur": "onBlur"; "onTextChange": "onTextChange"; "onPaste": "onPaste"; "onValidationError": "onValidationError"; "onTagEdited": "onTagEdited"; "inputTextChange": "inputTextChange"; }, ["dropdown", "templates"], ["*"]>;
#14 134.6                         ~~~~~~~~~~~~~~~~~~~~~~
#14 134.6 node_modules/ngx-chips/components/icon/icon.d.ts:3:21 - error TS2694: Namespace '"/app/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.
#14 134.6
#14 134.6 3     static ɵfac: i0.ɵɵFactoryDeclaration<DeleteIconComponent, never>;
#14 134.6                       ~~~~~~~~~~~~~~~~~~~~
#14 134.6 node_modules/ngx-chips/components/icon/icon.d.ts:4:21 - error TS2694: Namespace '"/app/node_modules/@angular/core/core"' has no exported member 'ɵɵComponentDeclaration'.
#14 134.6
#14 134.6 4     static ɵcmp: i0.ɵɵComponentDeclaration<DeleteIconComponent, "delete-icon", never, {}, {}, never, never>;
#14 134.6                       ~~~~~~~~~~~~~~~~~~~~~~
#14 134.6 node_modules/ngx-chips/core/pipes/highlight.pipe.d.ts:10:21 - error TS2694: Namespace '"/app/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.
#14 134.6
#14 134.6 10     static ɵfac: i0.ɵɵFactoryDeclaration<HighlightPipe, never>;
#14 134.6                        ~~~~~~~~~~~~~~~~~~~~
#14 134.6 node_modules/ngx-chips/core/pipes/highlight.pipe.d.ts:11:22 - error TS2694: Namespace '"/app/node_modules/@angular/core/core"' has no exported member 'ɵɵPipeDeclaration'.
#14 134.6
#14 134.6 11     static ɵpipe: i0.ɵɵPipeDeclaration<HighlightPipe, "highlight">;
#14 134.6                         ~~~~~~~~~~~~~~~~~
#14 134.6 node_modules/ngx-chips/tag-input.module.d.ts:19:21 - error TS2694: Namespace '"/app/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.
#14 134.6
#14 134.6 19     static ɵfac: i0.ɵɵFactoryDeclaration<TagInputModule, never>;
#14 134.6                        ~~~~~~~~~~~~~~~~~~~~
#14 134.6 node_modules/ngx-chips/tag-input.module.d.ts:m20:21 - error TS2694: Namespace '"/app/node_modules/@angular/core/core"' has no exported member 'ɵɵNgModuleDeclaration'.
#14 134.6
#14 134.6 20     static ɵmod: i0.ɵɵNgModuleDeclaration<TagInputModule, [typeof i1.TagInputComponent, typeof i2.DeleteIconComponent, typeof i3.TagInputForm, typeof i4.TagComponent, typeof i5.HighlightPipe, typeof i6.TagInputDropdown, typeof i7.TagRipple], [typeof i8.CommonModule, typeof i9.ReactiveFormsModule, typeof i9.FormsModule, typeof i10.Ng2DropdownModule], [typeof i1.TagInputComponent, typeof i2.DeleteIconComponent, typeof i3.TagInputForm, typeof i4.TagComponent, typeof i5.HighlightPipe, typeof i6.TagInputDropdown, typeof i7.TagRipple]>;
#14 134.6                        ~~~~~~~~~~~~~~~~~~~~~
#14 134.6 node_modules/ngx-chips/tag-input.module.d.ts:21:21 - error TS2694: Namespace '"/app/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectorDeclaration'.
#14 134.6
#14 134.6 21     static ɵinj: i0.ɵɵInjectorDeclaration<TagInputModule>;

**Comment by Gbuomprisco** [comment]
You'll have to either update your Angular version or downgrade ngx chips

**Comment by kesavanpos** [comment]
which version of ngx chips will work with Angular 9

**Comment by aiglesiasn** [comment]
@kesavanpos it worked for me with version 2.2.0.

**Comment by pardeshiAM** [comment]
"ngx-chips": "^2.1.0", 
Angular 9

**Comment by DarkoGjakovski** [comment]
Did you find a solution to this? I have the same exact error when updating Angular 9 to 10, tried with ngx chips 2.1.0, 2.2.2, 3.0.0, and still the same error.
