### ISSUE TITLE
Autocomplete problem: Rxjs functions

### ISSUE THREAD

**Issue by chanm003** [Gbuomprisco/ngx-chips#608]
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] support request/question
```

**Current behavior**
When using [autoCompleteObservable], I receive an error in console.

This continues to be a problem even after importing as identified in #546:
```
import 'rxjs/add/operator/debounceTime';
```

Error simply changes from
```
this.tagInput.onTextChange.debounceTime is not a function
    at TagInputDropdown.ngOnInit (ngx-chips.bundle.js:1353)
```
To a slighty different error:
```
this.tagInput.onTextChange.debounceTime(...).filter is not a function
    at TagInputDropdown.ngOnInit (ngx-chips.bundle.js:1354)

```

**What do you use to build your app?. Please specify the version**
Angular CLI 1.5.0

**Angular version:** 
Angular 5.0.0

**ngx-chips version:**
1.5.5

**rxjs version:**
5.5.2

**Comment by Gbuomprisco** [comment]
Have you also tried the latest version?

**Comment by chanm003** [comment]
Actually didn't realize I need to import even more rxjs operators
```
import 'rxjs/add/operator/filter';
import 'rxjs/add/operator/first';
```

Yes, 1.5.5 seems to respect the minimimTextLength.  Thanks

**Comment by Gbuomprisco** [comment]
I should actually add them to that file too, afterwards won't be needed at your end

**Comment by RedAB** [comment]
Hi, I am dealing with exactly the same issue after updating RxJS to 5.5 (using Angular 5) :

```
this.tagInput.onTextChange.asObservable(...).debounceTime is not a function
at TagInputDropdown.ngOnInit
```

Could you be more explicit about how you solved it ? Thanks !

**Comment by chanm003** [comment]
@RedAB 

I had to add three import statements to get it to work.   Please see comments above.

This link might be helpful: https://christianliebel.com/2017/07/import-rxjs-correctly/
